### ISSUE TITLE
Public site is broken

### ISSUE THREAD

**Issue by ifranch** [metrotranscom/doorway#35]
**Describe the bug**
There is a compilation error when trying to bring up the public site. This was introduced by https://github.com/metrotranscom/doorway/pull/21

**To Reproduce**
Run yarn:dev:public

**Expected behavior**
There should not be any errors

**Screenshots**
![image](https://user-images.githubusercontent.com/67125998/230501996-b5d62855-5f71-4a51-9736-81fe43aa5a90.png)

**Desktop (please complete the following information):**

**Additional context**
